version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - "27017:27017"
#    command:
#      --replSet rs1
